server:
  port: 9000

kafka:
  consumer:
    bootstrap: localhost:29092
    group: test-group
    topic: test-topic
    properties:
      partition:
        assignment:
          strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
# spring.kafka.consumer.properties.partition.assignment.strategy=\
# org.apache.kafka.clients.consumer.RoundRobinAssignor.
# https://docs.spring.io/spring-kafka/reference/html/