server:
  port: 8000

kafka:
  producer:
    bootstrap: localhost:29092
    topic: test-topic

connection:
  timeout: 60000

logging:
  level:
    org:
      apache:
        http: DEBUG
        kafka: ERROR
      springframework:
        cloud:
          sleuth: INFO
    nodeValue: DEBUG